export const en = {
    amount: "Amount",
    amountOfIngredients: "Amount of ingredients: ",
    approach: "Approach",
    cancel: "Cancel",
    category: "Category",
    confirmDelete: "Do you want to delete this recipe?",
    cookbook: 'Cookbook',
    created: "Created",
    delete: "Delete",
    dessert: "Dessert",
    dinner: "Dinner",
    dishName: "Name of the dish",
    goToRecipe: "Go to recipe",
    information: "Information",
    ingredient: "Ingredient",
    ingredients: "Ingredients",
    instructions: "Instructions",
    language: 'en',
    maxTime: "Max time",
    minTime: "Min time",
    missingText: "Missing text",
    name: "Name",
    portions: "Portions",
    remove: "Remove",
    step: "Step",
    submit: "Submit",
    unit: "Unit",
    filter: "Filter",
    noFilter: "No filter",
    mainCategory: "Main category",
    subCategories: "Sub category",
    search: 'Search',
    drinks: "Drinks",
    breakfast: "Breakfast",
    christmas: "Christmas",
    easter: "Easter",
    summer: "Summer",
    icecream: "Icecream",
    cake: "Cake",
    vegan: "Vegan",
    smoothie: "Smoothie",
    milkshake: "Milkshake",
    cookies: "Cookies",
    cocktail: "Cocktail",
    mexican: "Mexican",
    italian: "Italian",
    burger: "Burger",
    pizza: "Pizza",
    pasta: "Pasta",
    sauce: "Sauce",
    image: 'Picture',
    upload: 'Upload',

    g: ["g", "Gram"],
    kg: ["kg", "Kilogram"],
    ml: ["ml", "Milliliters"],
    dl: ["dl", "Desiliters"],
    l: ["l", "Liters"],
    pcs: ["stk", "Piece"],
    tbsp: ["ss", "Tablespoon"],
    tsp: ["ts", "Teaspoon"],
};