export const no = {
    amount: "Mengde",
    amountOfIngredients: "Antall ingredienser: ",
    approach: "Fremgangsmåte",
    cancel: "Avbryt",
    category: "Kategori",
    confirmDelete: "Vil du slette denne oppskriften?",
    cookbook: 'Kokebok',
    created: "Opprettet",
    delete: "Slett",
    dessert: "Dessert",
    dinner: "Middag",
    dishName: "Navn på retten",
    goToRecipe: "Gå til oppskriften",
    information: "Informasjon",
    ingredient: "Ingrediens",
    ingredients: "Ingredienser",
    instructions: "Instruksjoner",
    language: 'no',
    maxTime: "Max tid",
    minTime: "Min tid",
    missingText: "Mangler tekst",
    name: "Navn",
    portions: "Porsjoner",
    remove: "Fjern",
    step: "Steg",
    submit: "Send inn",
    unit: "Enhet",
    filter: "Filtrer",
    noFilter: "Ingen filter",
    mainCategory: "Hovedkategori",
    subCategories: "Underkategorier",
    search: 'Søk',
    drinks: "Drikke",
    breakfast: "Frokost",
    christmas: "Jul",
    easter: "Påske",
    summer: "Sommer",
    icecream: "Iskrem",
    cake: "Kake",
    vegan: "Vegansk",
    smoothie: "Smoothie",
    milkshake: "Milkshake",
    cookies: "Kjeks",
    cocktail: "Cocktail",
    mexican: "Meksikansk",
    italian: "Italiensk",
    burger: "Burger",
    pizza: "Pizza",
    pasta: "Pasta",
    sauce: "Saus",
    image: 'Bilde',
    upload: 'Last opp',

    g: ["g", "Gram"],
    kg: ["kg", "Kilogram"],
    ml: ["ml", "Milliliter"],
    dl: ["dl", "Desiliter"],
    l: ["l", "Liter"],
    pcs: ["stk", "Stykker"],
    tbsp: ["ss", "Spiseskje"],
    tsp: ["ts", "Teskje"],
};